kind = "web"
previewPath = "/"
title = "CraftedSnippets Co."
version = "1.0.0"
id = "artifacts/craftedsnippets"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20189

[services.development]
run = "pnpm --filter @workspace/craftedsnippets run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/craftedsnippets", "run", "build" ]
serve = "static"
publicDir = "artifacts/craftedsnippets/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20189"
BASE_PATH = "/"
